### ISSUE TITLE
Implement Left Side in Detail page

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#103]
**Todo**

- [x] 필요한 컴포넌트 조립
- [x] 채널 정보 데이터 받아오기
- [x] 정보에 따라 보여줄 내용과 보여주지 않을 내용 분기처리하기
- [x] source 링크에 새창열림 아이콘 추가
- [x] 채널 인포 userName, channelName 스타일 유동적으로 변경(말줄임 표시 관련)
- [x] follow on sns 아이콘 적용

**ETC**

- Opinions & Problems
