### ISSUE TITLE
Implement Rigjht Side in Detail page

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#113]
**Todo**

- [x] gif 제목 출력해주기
- [x] 해당 gif 보여주기
- [x] favorite, share, embaded 버튼 넣기
- [x] 데이터 받아와서 태그 리스트 뿌려주기
- [ ] Related Clips
- [ ] Related GIFs

**Assignee**

- None

**ETC**

- Opinions & Problems
