### ISSUE TITLE
SearchSuggestions with keyboard 

### ISSUE THREAD

**Issue by sosoYim** [team-GIFT/gift#125]
**Todo**

- [ ] 아래 방향키를 누르면 연관 검색어가 뜬다.
- [ ] 검색 인풋창을 포함하여 연관검색어 내에서 위 아래 방향키로 키보드 트래핑
- [ ] esc를 누르면 연관 검색어가 보이지 않는다

**Assignee**

- @sosoYim 

**ETC**

- Opinions & Problems
