### ISSUE TITLE
Responsive Header

### ISSUE THREAD

**Issue by sosoYim** [team-GIFT/gift#127]
**Todo**

- [x] Minimize rerender with viewport size state
- [x] Global Nav has isMobile props to render by condition
- [x] SubMenu layout change -> flex-direction:column;

**Assignee**

- @sosoYim 

**ETC**

**Comment by sosoYim** [comment]
useWindowSize from react-use
https://github.com/streamich/react-use/blob/master/docs/useWindowSize.md

**Comment by sosoYim** [comment]
리덕스로 뷰포트 브레이크 포인트에 대한 상태를 가지고 있다면 수월할 것

**Comment by sosoYim** [comment]
다음 스프린트에서 할 것 : 모바일 기기를 고려하여 호버외에 클릭 이벤트 설정
