### ISSUE TITLE
Proposal) 발표 전 마지막 Checklist

### ISSUE THREAD

**Issue by ulgoon** [team-GIFT/gift#136]
**Todo**

기능 구현 후 발표 전까지 진행하셔야 할 Task들을 전달드립니다.

- [x] Clean up branch(only main, develop branch on remote)
- [ ] [Update README.md](https://www.makeareadme.com/)
- [x] Publish release
- [ ] Update wiki, issues, projects
   - [ ] wiki
   - [x] issues
   - [x] projects 
- [x] 발표자료 완성 및 시연 시나리오 구성
- [x] 기능별 시연 영상 녹화
- [ ] (optional) 코드 리팩토링
- [x] (optional) 배포하기(recommend: [heroku](https://blog.heroku.com/deploying-react-with-zero-configuration) )

**Assignee**

- None

**ETC**

- Opinions & Problems

If you have any questions, leave a comment below.
