### ISSUE TITLE
Modify Detail page

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#139]
**Todo**

- [x] Related Gif, Related Stickers  id 받을 수 있게 수정
- [x] Detail 페이지에서 GIf id 잘못 들어왔거나, detail로만 들어오면 페이지 리다이렉션 하기
- [x] 페이지 타이틀 바꿀 수 있게 처리하기
- [x] Related GIf Grid 컴포넌트 적용하기
- [x] search 페이지에서 Tag List 사용 할 경우 처리해주기

**ETC**

- Opinions & Problems
