### ISSUE TITLE
전체 일정 수립

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#14]
**Todo**

- [x] Daily scrum 규칙 정하기
- [x] Milestone에 Sprint 설정 하기 
- [x] Sprint 2 세부 일정 수립
- [x] Sprint 3 세부 일정 수립
- [x] Sprint 4 세부 일정 수립

**Assignee**

- @sosoYim @congaweb @jkpark104 

**ETC**

- Opinions & Problems
