### ISSUE TITLE
Global style 컴포넌트 제작

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#17]
**Todo**

- [x] Normalize를 활용하여 global style 컴포넌트 제작
- [x] color 변환 util 컴포넌트 제작
- [x] color set 컴포넌트 제작

**Description**

- normalize 및 공통 스타일 적용한 스타일 컴포넌트 제작
- hex 코드를 rgb(a)로 변환해주는 util 함수 제작
- color set을 저장한 컴포넌트 제작

**ETC**

- Opinions & Problems
