### ISSUE TITLE
Create Card Component

### ISSUE THREAD

**Issue by jkpark104** [team-GIFT/gift#22]
**Todo**
- [x] Card.tsx
- [x] Card.styled.tsx
- [x] Card.stories.tsx
- [x] Card.types.ts

**Assignee**

- @jkpark104 

**ETC**

- Opinions & Problems
