### ISSUE TITLE
Create SvgIcon component

### ISSUE THREAD

**Issue by sosoYim** [team-GIFT/gift#25]
**Todo**

- [x] Adapte SVG Sprite technique
- [x] Define types which includes svg id
- [x] Icon components needs those props :  type, width, height, fill
- [x] exported icons : favorite, favorite-added, link, sound-on, sound-off, ??

**Assignee**

- None

**ETC**

- Should we seperate every types from component file ? 
- Do we need more props for SvgIcon component ? Please comment here !

**Comment by sosoYim** [comment]
크기 설정 및 접근성에 대해서는 고민이 더 필요함
