### ISSUE TITLE
Implement A11yHidden component

### ISSUE THREAD

**Issue by sosoYim** [team-GIFT/gift#35]
**Todo**

- [x] 컴퍼넌트는 화면에 시각적으로 감춰져야 한다.
- [x] 보조기기에서는 잡힐 수 있어야 한다.(랜더트리에 존재해야 한다.)
- [x] focusable한 요소라면 포커스 되었을 때 모습이 보여야 한다.

**ETC**

- Opinions & Problems
