### ISSUE TITLE
Create Loading Spinner component

### ISSUE THREAD

**Issue by congaweb** [team-GIFT/gift#39]
**Todo**

- [x] 접근성을 위해 index.html에 스피너를 위한 영역 설정하기
- [x] Loading Spinner 구조 잡기
- [x] 스타일 입히기
- [x] 타입 설정하기
- [x] 애니메이션 적용하기
- [x] Loading시 동작하게 만들기

**ETC**

- Opinions & Problems
