### ISSUE TITLE
Implement SearchBar animation

### ISSUE THREAD

**Issue by sosoYim** [team-GIFT/gift#43]
**Todo**

- [ ] Placeholder 위치에 문장들이 세로 캐러셀 처럼 동작한다.
- [ ] 하나의 문장이 올라가면 다음 문장이 placeholder 위치에 있다.
- [ ] 마지막 문장이 위치하면 첫번째 문장으로 바꿔치기 한다.

**ETC**

- Opinions & Problems

**Comment by sosoYim** [comment]
다음 sprint로
