### ISSUE TITLE
Create Card Info Detail

### ISSUE THREAD

**Issue by jkpark104** [team-GIFT/gift#49]
**Todo**

- [x] #32
- [x] 채널 정보 설명 용 컴포넌트 #103 
- [x] GIF 상단 이미지 제목  컴포넌트 #113 
- [x] GIF 이미지 컴포넌트#113 
- [x] Favorite, Share, Embed 버튼 컴포넌트#113 
- [x] Follow on 영역 컴포넌트 #103 
- [x] #60
- [x] #66

**Description**

- 디테일 페이지에 들어가는 컴포넌트를 컨트롤 하기 위한 이슈입니다.

**ETC**

- Opinions & Problems
