### ISSUE TITLE
Create Search Result

### ISSUE THREAD

**Issue by jkpark104** [team-GIFT/gift#50]
**Todo**

- [x] 검색어 및 결과로 나오는 GIF 갯수 띄워주기 (cancel)
- [x] 유사 추천어 태그로 표시 
  - Create tag component
- [x] 채널 검색 결과
  - #32  
- [x] GIPHY Clips 카테고리 결과
  - 값을 주지 않아서 취소
- [x] GIFs 혹은 Stickers 결과 토글로 보기
  - #51 
  - Create toggle component
- [x] 검색 결과가 없을 경우 안내 문구 띄워주기

**Assignee**

- None

**ETC**

- Opinions & Problems
