### ISSUE TITLE
Create Card Container

### ISSUE THREAD

**Issue by jkpark104** [team-GIFT/gift#53]
**Todo**

- [x] Trending 컨테이너 구현
- [x] Artists 컨테이너 구현
- [x] Clips 컨테이너 구현

**Assignee**

- @jkpark104 

**ETC**

- Opinions & Problems
