### ISSUE TITLE
Implement redux types

### ISSUE THREAD

**Issue by jkpark104** [team-GIFT/gift#99]
**Todo**

- [x] redux 관련 코드 타입 명시하기
- [x] useAppDispatch & useAppSelector
- [x] add storyGifsSelector
- [x] modify initialState structure
- [x] implement fetchStoryGifs AsyncThunk

**Assignee**

- @jkpark104 

**ETC**

- Opinions & Problems
